import { NextResponse } from "next/server";
import { getProfile, saveProfile } from "@/lib/data";
import { errorResponse, refreshPublicPages, requireAdmin } from "@/lib/api";
import type { Profile } from "@/lib/types";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

export async function GET() {
  try {
    await requireAdmin();
    return NextResponse.json({ profile: await getProfile() });
  } catch (error) {
    return errorResponse(error);
  }
}

export async function PUT(request: Request) {
  try {
    await requireAdmin();

    const body = (await request.json()) as Partial<Profile>;
    const current = await getProfile();

    // `stats` is generated by the GitHub sync — never let the UI clobber it.
    const merged: Profile = {
      ...current,
      ...body,
      stats: current.stats,
      updatedAt: new Date().toISOString(),
    };

    const mode = await saveProfile(merged);
    refreshPublicPages();

    return NextResponse.json({ profile: merged, mode });
  } catch (error) {
    return errorResponse(error);
  }
}
